[phases.setup]
cmds = [
    "apt-get update && apt-get install -y --no-install-recommends python3-pip",
    "pip install --no-cache-dir --upgrade pip"
]
[phases.start]
cmds = [
    "pip install -r requirements.txt",  # Add this line to install dependencies
    "python main.py"                    # Original command
]